import sqlite3
import pandas as pd
import yaml
import os
import json
from groq import Groq
from dotenv import load_dotenv

load_dotenv()

DB_PATH = 'eliseai_metrics.db'
GROQ_API_KEY = os.environ.get("GROQ_API_KEY")

# Load the semantic layer to "prove" governance in the UI
with open("metrics.yaml", "r") as f:
    SEMANTIC_LAYER = yaml.safe_load(f)

with open("schema.sql", "r") as f:
    DB_SCHEMA = f.read()

def run_query(sql):
    conn = sqlite3.connect(DB_PATH)
    try:
        df = pd.read_sql_query(sql, conn)
    except Exception as e:
        df = pd.DataFrame({"Error": [str(e)]})
    finally:
        conn.close()
    return df

def ask_copilot(query_text: str):
    """
    Uses Groq LLM to dynamically parse intent, enforce metric governance from rules, 
    generate SQL, execute against SQLite, and pick a chart type.
    """
    if not GROQ_API_KEY:
        return {
            "sql": "-- Configuration Error",
            "dataframe": pd.DataFrame({"Error": ["Missing GROQ_API_KEY"]}),
            "narrative": "The system is missing the Groq API Key required for dynamic Text-to-SQL logic.",
            "chart_type": "table",
            "x_col": None,
            "y_col": None,
            "title": "System Configuration Alert"
        }

    client = Groq(api_key=GROQ_API_KEY)
    
    system_prompt = f"""You are a brilliant, elite Senior Finance Data Analyst working as an AI Copilot for an Enterprise SaaS company.
Your job is to answer executive questions strictly using data from a predefined dimensional database.
You must adhere EXACTLY to the business rules in the Semantic Layer when calculating metrics. DO NOT hallucinate columns or tables.

## Database Schema (SQLite):
```sql
{DB_SCHEMA}
```

## Semantic Layer Definitions (Follow these rules strictly):
```yaml
{yaml.dump(SEMANTIC_LAYER, default_flow_style=False)}
```

You must return a raw JSON object string with EXACTLY the following keys and data types.
{{
    "sql": "The raw SQLite string to execute, fully executable, no markdown wrapping, no formatting.",
    "narrative": "A plain English footnote explaining the metric calculation rules applied and the insight derived.",
    "chart_type": "One of: 'line', 'bar', 'scatter', 'table'",
    "x_col": "Name of the column to use for the x-axis (or null if table)",
    "y_col": "Name of the column or array of column names for the y-axis (or null if table)",
    "size_col": "Name of column for scatter plot size (optional, null if not scatter)",
    "title": "A short, professional title for the chart"
}}

Rules for JSON:
- Return ONLY the JSON object. Do not wrap it in markdown block quotes (```json). Do not add conversational text.
- Double quotes around keys.
- Ensure the SQL is completely valid for SQLite based on the provided schema.
"""

    try:
        completion = client.chat.completions.create(
            model="llama-3.3-70b-versatile", 
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": query_text}
            ],
            temperature=0.0,
            response_format={"type": "json_object"}
        )
        
        response_content = completion.choices[0].message.content
        parsed = json.loads(response_content)
        
        sql = parsed.get("sql", "").strip()
        
        # Guard against LLM accidentally wrapping SQL in markdown inside the JSON
        if sql.startswith("```sql"): sql = sql[6:]
        if sql.startswith("```"): sql = sql[3:]
        if sql.endswith("```"): sql = sql[:-3]
        sql = sql.strip()

        df = run_query(sql)
        
        # Handle bad SQL generated by the LLM
        if "Error" in df.columns:
            narrative = f"⚠️ Query Execution Error. The LLM generated invalid SQL based on the schema.\n\nError details: {df['Error'][0]}"
            parsed["chart_type"] = "table"
            parsed["title"] = "Query Generation Failed"
        else:
            narrative = parsed.get("narrative", "")
            
        return {
            "sql": sql,
            "dataframe": df,
            "narrative": narrative,
            "chart_type": parsed.get("chart_type", "table"),
            "x_col": parsed.get("x_col"),
            "y_col": parsed.get("y_col"),
            "size_col": parsed.get("size_col"),
            "title": parsed.get("title", "Financial Analysis")
        }
        
    except Exception as e:
        return {
            "sql": f"-- Execution Error:\n-- {str(e)}",
            "dataframe": pd.DataFrame({"System Error": [str(e)]}),
            "narrative": f"The LLM Copilot Engine encountered a critical exception communicating with Groq or parsing JSON.",
            "chart_type": "table",
            "x_col": None,
            "y_col": None,
            "title": "System Alert"
        }
